constants:
  api:
    prefix: /api/order

# server.port 8080으로 통일
server:
  port: 8080

spring:
  application:
    name: order-service
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-auth-prod.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.222.157.157:5011/my_eats_order?useInformationSchema=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: green1
    password: spring502
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    # 서비스명(kafka) + 네임스페이스(infra) + 포트(9092)
    bootstrap-servers: kafka.infra.svc.cluster.local:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      # 서비스별로 고유한 그룹 ID를 갖도록 설정
      group-id: ${spring.application.name}-group

